{% set name = "nengo-dl" %}
{% set version = "3.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nengo-dl-{{ version }}.tar.gz
  sha256: 81e8e84c9ed771452cb2b04fbb323a6e43ddfb7f3fa1fa3d73e267cd4f32cfba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jinja2
    - nengo >=3.0.0
    - numpy
    - packaging
    - progressbar2
    - python >=3.6
    - tensorflow >=2.2.0

test:
  imports:
    - nengo_dl
    - nengo_dl.tests

about:
  home: https://www.nengo.ai/nengo-dl
  summary: Deep learning integration for Nengo
  license: LicenseRef-NENGO
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - Tobias-Fischer
